# Generated by Django 4.1.4 on 2022-12-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payments_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='service',
            field=models.CharField(choices=[('NF', 'Netflix'), ('AP', 'Amazon Video'), ('ST', 'Star +'), ('PM', 'Paramount +')], default='NF', max_length=2),
        ),
    ]
