# Generated by Django 4.1.4 on 2022-12-21 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('versionedpayments', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('paymet_date', models.DateField(auto_now=True)),
                ('expiracion_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(choices=[('NF', 'Netflix'), ('AP', 'Amazon Video'), ('ST', 'Star +'), ('PM', 'Paramount +')], default='NF', max_length=2),
        ),
        migrations.RenameModel(
            old_name='ExpiredPayments',
            new_name='Expired_payments',
        ),
        migrations.DeleteModel(
            name='PaymentUser',
        ),
        migrations.AddField(
            model_name='payment_user',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versionedpayments.services'),
        ),
        migrations.AddField(
            model_name='payment_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expired_payments',
            name='payment_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versionedpayments.payment_user'),
        ),
    ]
